[package]
name = "rust-todo"
version = "0.1.0"
authors = ["Patrick McLennan <patrick.a.mclennan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"